### ISSUE TITLE
Getting a Overflowerror trying to use postgres

### ISSUE THREAD

**Issue by DreiPixel** [fake-name/xA-Scraper#115]
im trying to use the scraper to get images from my patreon and i have set up postgres and this program for that.

the problem is it doesnt work correctly and im getting a error everytime

`
Job "pat (trigger: interval[0:05:00], next run at: 2018-05-12 13:15:00 CEST)" raised an exception
Traceback (most recent call last):
  File "/home/pi/xA-Scraper/venv/lib/python3.5/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "./main.py", line 64, in runScraper
    instance.go(ctrlNamespace=managed_namespace)
  File "/home/pi/xA-Scraper/rewrite/modules/scraper_base.py", line 486, in go
    nameList = self.getNameList()
  File "/home/pi/xA-Scraper/rewrite/modules/patreon/patreonScrape.py", line 454, in getNameList
    self.getCookie()
  File "/home/pi/xA-Scraper/rewrite/modules/patreon/patreonScrape.py", line 78, in getCookie
    self.wg._syncCookiesFromFile()
  File "/home/pi/xA-Scraper/venv/lib/python3.5/site-packages/WebRequest/WebRequestClass.py", line 769, in _syncCookiesFromFile
    self.cj.save("cookietemp.lwp")
  File "/usr/lib/python3.5/http/cookiejar.py", line 1880, in save
    f.write(self.as_lwp_str(ignore_discard, ignore_expires))
  File "/usr/lib/python3.5/http/cookiejar.py", line 1867, in as_lwp_str
    r.append("Set-Cookie3: %s" % lwp_cookie_str(cookie))
  File "/usr/lib/python3.5/http/cookiejar.py", line 1828, in lwp_cookie_str
    time2isoz(float(cookie.expires))))
  File "/usr/lib/python3.5/http/cookiejar.py", line 104, in time2isoz
    dt = datetime.datetime.utcfromtimestamp(t)
OverflowError: timestamp out of range for platform time_t
`

Sqlite works normal but its slow i guess?

**Comment by DreiPixel** [comment]
ok after redownloading this program it works?

**Comment by fake-name** [comment]
A site was pushing a cookie with an expiration time that exceeds the representable range of `time_t`, which is a `uint32_t` (e.g. [after 2038](https://en.wikipedia.org/wiki/Year_2038_problem)).

It wasn't re-downloading that actually fixed anything, but rather the fact that redownloading incidentally cleared your cookies.
