### ISSUE TITLE
Patreon scrapper asks for a Captcha to be filled out

### ISSUE THREAD

**Issue by Two-Tone** [fake-name/xA-Scraper#131]
I looked and have not seen anything about Patreon needing a captcha to be filled out, but the scrapper is reporting I need to fill out one.
```

Job "pat (trigger: interval[0:02:00], next run at: 2018-06-06 20:04:00 EDT)" raised an exception
Traceback (most recent call last):
  File "/home/two/xA-Scraper-master/venv/lib/python3.4/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "./main.py", line 58, in runScraper
    instance.go(ctrlNamespace=managed_namespace)
  File "/home/two/xA-Scraper-master/rewrite/modules/scraper_base.py", line 487, in go
    nameList = self.getNameList()
  File "/home/two/xA-Scraper-master/rewrite/modules/patreon/patreonScrape.py", line 454, in getNameList
    self.getCookie()
  File "/home/two/xA-Scraper-master/rewrite/modules/patreon/patreonScrape.py", line 75, in getCookie
    current = self.get_json("/login", postData=login_data, retries=1)
  File "/home/two/xA-Scraper-master/rewrite/modules/patreon/patreonScrape.py", line 109, in get_json
    retryQuantity = retries)
  File "/home/two/xA-Scraper-master/venv/lib/python3.4/site-packages/WebRequest/WebRequestClass.py", line 135, in getpage
    return self.__getpage(requestedUrl, *args, **kwargs)
  File "/home/two/xA-Scraper-master/venv/lib/python3.4/site-packages/WebRequest/WebRequestClass.py", line 577, in __getpage
    err_content=err_content, err_code=err_code, err_reason=err_reason)
WebRequest.Exceptions.FetchFailureError: <FetchFailureError 400 -> 'BAD REQUEST' for url: https://api.patreon.com/login ({b'{\n    "errors": [\n        {\n            "code": null,\n            "code_name": "FlaggedAsBot",\n            "detail": "Please fill out the captcha to finish!",\n            "id": "",\n            "status": "400",\n            "title": "Please fill out the captcha to finish!"\n        }\n    ]\n}'})>
```

**Comment by fake-name** [comment]
Huh, I didn't know patreon added captchas.

**Comment by Two-Tone** [comment]
It may be a new bot specific thing.  I never noticed a captcha when logging in via my browsers.

**Comment by fake-name** [comment]
Almost certainly using a normal browser doesn't trigger the relevant checks.

**Comment by Two-Tone** [comment]
Is there a way to manually import my patreon cookie from my browser as a workaround?

**Comment by fake-name** [comment]
The cookies are stored in a file on-disk called `cookies.lwp`.

It's in a fairly standard-ish format called Set-Cookie3 and/or LWP, though figuring out how to get to there from a browser is probably fiddly.

If you look in the file (it's just ASCII text), you might be able to figure out how to convert from a browser cookie to a lwp cookie.
