### ISSUE TITLE
pixiv scraping errors

### ISSUE THREAD

**Issue by rawesomeawesome** [fake-name/xA-Scraper#164]
when scraping any work from pixiv it returns a runtime error

```
Main.PxGet.Thread-1 - INFO - Pages for 11 remaining = 370
Main.WebRequest - INFO - Fetching content at URL: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=<somesuchpixivid>
Main.WebRequest - INFO - Request for URL: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=<sucharealpixivid> succeeded at Tue Jul 24 06:55:47 2018 On Attempt 1. Recieving...
Main.WebRequest - INFO - URL fully retrieved.
Main.WebRequest - INFO - Compression type = gzip. Content Size compressed = 11.762K. Decompressed = 58.992K. File type: text/html; charset=UTF-8.
Main.PxGet.Thread-1 - ERROR - Unknown error in page retrieval!
Main.PxGet.Thread-1 - ERROR - Source URL = 'http://www.pixiv.net/member_illust.php?mode=medium&illust_id=<yupapixivid>'
Main.PxGet.Thread-1 - ERROR - Traceback (most recent call last):
  File "/mnt/c/Users/<myusername>/OneDrive/Desktop/xA-Scraper-master/xA-Scraper-master/rewrite/modules/scraper_base.py", line 413, in getArtist
    ret = self._fetch_retrier(dlPathBase, pageURL, artist)
  File "/mnt/c/Users/<myusername>/OneDrive/Desktop/xA-Scraper-master/xA-Scraper-master/rewrite/modules/scraper_base.py", line 378, in _fetch_retrier
    ret = self._getArtPage(*args, **kwargs)
  File "/mnt/c/Users/<myusername>/OneDrive/Desktop/xA-Scraper-master/xA-Scraper-master/rewrite/modules/px/pxScrape.py", line 397, in _getArtPage
    raise RuntimeError("Unknown content type!")
RuntimeError: Unknown content type!
```

im not sure of the cause, as the links it pulls seem to be valid upon entering them into a browser

**Comment by fake-name** [comment]
I assume it's probably a type of media (or page layout) that I haven't specifically written handling for.

Can you give me a URL for a page that exhibits this behaviour?

**Comment by fake-name** [comment]
Closing due to lack of response.
