### ISSUE TITLE
Message "Another instance of the tumblr scraper is running."

### ISSUE THREAD

**Issue by jimhsu** [fake-name/xA-Scraper#23]
Hi,

My Patreon scraper stopped working all of a sudden; subsequent runs (auto or manually) produce the following message:

```
Another instance of the tumblr scraper is running.
Not starting
```

I found the respective lines in scraper_base.py and it seems to be some sort of activity check with **is_another_active**, but nothing was running. I even tried shutting down the main script with no effect. I ended up commenting the whole block out, and the scraper seems to work properly, but this seems to be a consistency check gone awry. Could an unclean shutdown of a scraper (Ctrl+C, system reboot, etc) cause this?

**Comment by jimhsu** [comment]
Note: after letting the script run and checking terminal output, it appears that the script terminates with some sort of uncaught EOF (pages remaining for the artist in question = 0):

```
Main - CRITICAL - Uncaught exception!
Main - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/myblocks/scrapers/xascraper/manage/__main__.py", line 90, in <module>
    go()
  File "/home/myblocks/scrapers/xascraper/manage/__main__.py", line 84, in go
    two_arg_go(sys.argv[1], sys.argv[2])
  File "/home/myblocks/scrapers/xascraper/manage/__main__.py", line 37, in two_arg_go
    do_fetch([param])
  File "/home/myblocks/scrapers/xascraper/manage/scrape_manage.py", line 62, in do_fetch
    do_plugin(plg)
  File "/home/myblocks/scrapers/xascraper/manage/scrape_manage.py", line 43, in do_plugin
    plg.runScraper(namespace)
  File "/home/myblocks/scrapers/xascraper/rewrite/modules/scraper_base.py", line 523, in runScraper
    instance.go(ctrlNamespace=managedNamespace)
  File "/home/myblocks/scrapers/xascraper/rewrite/modules/scraper_base.py", line 507, in go
    errored  |= future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/myblocks/scrapers/xascraper/rewrite/modules/patreon/patreonScrape.py", line 295, in getArtist
    artist_decoded = json.loads(artist_undecoded)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Main.PatreonGet.StatusMgr - INFO - Unoading PatreonGet
```

**Comment by fake-name** [comment]
That.... that is really strange. Did you add artists for the scraper to scrape through the web-ui or something?

I think I might not have blocked that, and it won't work. The patreon scraper scrapes everyone you support automatically, and has no facilities for filtering at all.

**Comment by fake-name** [comment]
The `Another instance of the tumblr scraper is running.` was due to some locking I added to try to fix strange behaviour I've been seeing from the tumblr scraper. I forgot to add the associated cleanup it needs. 

Right now, there are some status flags in the database which are set when a plugin starts and stops. This is to try to prevent re-entrancy as a result of the scheduler, or some mysterious recursion I've been seeing from the TumblrScraper that I have not been able to completely figure out the cause of. When a plugin starts, it checks if the flag in the database is set, and if it is, it aborts rather then starting another instance.

Normally, when a plugin exits, it should clear the flag, but an unexpected exit can cause that to fail. In the other project where I used similar logic (https://github.com/fake-name/MangaCMS), I reset the run-states when the main scheduler starts, but I forgot to implement that here. 2ae092a2d9088705f117d6e2e590a84b4b57d8c2 implements that, as well as a management command to forcefully reset any stuck run-states (`python3 -m manage reset-run-state`).

**Comment by jimhsu** [comment]
Thanks, that resolved all problems on my end. For the error message, you were correct that it turned out to be an errant entry in the psql database.

**Comment by fake-name** [comment]
Yeah, a lot of the architecture for the project has kind of grown organically, and it has a fair bit of things where features kind of get wedged into the scraper architecture in not-so-elegant ways. Since I've implemented most of it for myself, I kind of know "don't do this thing in the interface", but it's not actually *documented* anywhere. 

It's good to find that kind of thing and fix it properly. Thanks!
