### ISSUE TITLE
KeyError: 'ng'

### ISSUE THREAD

**Issue by Aidolii** [fake-name/xA-Scraper#288]
I updated my xa-Scraper today and when I try to run it I get this error:
```
Sqlite database path: 'sqlite:///D:\xA-Scraper\sqlite_db.db'
Traceback (most recent call last):
  File "db_migrate.py", line 7, in <module>
    from xascraper import app, db
  File "D:\xA-Scraper\xascraper\__init__.py", line 74, in <module>
    from . import views
  File "D:\xA-Scraper\xascraper\views\__init__.py", line 2, in <module>
    from . import main_views
  File "D:\xA-Scraper\xascraper\views\main_views.py", line 28, in <module>
    import main
  File "D:\xA-Scraper\main.py", line 57, in <module>
    (ngs.GetNg,      settings[ "ng"]["runInterval"],  "ng"),
KeyError: 'ng'
```

**Comment by Aidolii** [comment]
Apparently I had to update my settings.py with what is shown here: https://github.com/fake-name/xA-Scraper/commit/04b5bf118abcc482752d5a784adc6207928b639b
