### ISSUE TITLE
Error on attempting to access server

### ISSUE THREAD

**Issue by mmsterful** [fake-name/xA-Scraper#4]
I might as well create a new issue, since this is a separate problem. I re-cloned the repo for the new version, made a new database, changed the credentials in wsgi_server.py, copied over my old settings.py, and got this upon trying to access the server:

```
[23/Oct/2016:14:42:32] ENGINE Bus STARTING
[23/Oct/2016:14:42:32] ENGINE Started monitor thread '_TimeoutMonitor'.
[23/Oct/2016:14:42:32] ENGINE Started monitor thread 'Autoreloader'.
[23/Oct/2016:14:42:33] ENGINE Serving on http://0.0.0.0:6543
[23/Oct/2016:14:42:33] ENGINE Bus STARTED
Main.WebSrv - WARNING - No userID found for request to '/'. Redirecting to login.
Main.WebSrv - INFO - Request from 127.0.0.1 for path - /login!
Main.WebSrv - ERROR - Page rendering error! url: login
Main.WebSrv - ERROR - Traceback (most recent call last):
  File "/mnt/h/xA-Scraper/wsgi_server.py", line 144, in getPageNoAuth
    return self.getResponse(normalized_path)
  File "/mnt/h/xA-Scraper/wsgi_server.py", line 88, in getResponse
    with open(reqPath, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/[username]/xA-Scraper/Content/login'

[23/Oct/2016:14:42:44] ENGINE TopLevelLookupException("Cant locate template for uri 'error.mako'",)
Traceback (most recent call last):
  File "/mnt/h/xA-Scraper/wsgi_server.py", line 144, in getPageNoAuth
    return self.getResponse(normalized_path)
  File "/mnt/h/xA-Scraper/wsgi_server.py", line 88, in getResponse
    with open(reqPath, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/[username]/xA-Scraper/Content/login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/mako/lookup.py", line 245, in get_template
    return self._check(uri, self._collection[uri])
KeyError: 'error.mako'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1078, in communicate
    req.respond()
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 866, in respond
    self.server.gateway(self).respond()
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1969, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/cherrypy/_cptree.py", line 299, in __call__
    return app(environ, start_response)
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/pyramid/router.py", line 223, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 217, in wrapper
    response = view(context, request)
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 466, in mapped_view
    return _mapped_view(context, request)
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 507, in _requestonly_view
    response = view(request)
  File "/mnt/h/xA-Scraper/wsgi_server.py", line 154, in getPageNoAuth
    pgTemplate = self.lookupEngine.get_template("error.mako")
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/mako/lookup.py", line 259, in get_template
    "Cant locate template for uri %r" % uri)
mako.exceptions.TopLevelLookupException: Cant locate template for uri 'error.mako'
```

Seems like the server's getting confused and trying to load a login page in the wrong way.

Note that the weird paths are because I'm running this on an unholy and possibly cursed combination of Windows Subsystem for Linux and the Windows version of Postgres; it didn't seem to cause any problems with the older version, so it's probably unrelated.

I wouldn't say my project is of critical importance, so don't go wasting your Sunday trying to fix an annoying bug on my account. :P

**Comment by fake-name** [comment]
> `FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/[username]/xA-Scraper/Content/login'`

This is the web-server saying it can't find the `login.mako` file, which it's expecting in the directory `/mnt/c/Users/[username]/xA-Scraper/Content/` (the server tries to render a template (e.g. mako) file first, and falls back to serving plain files if it can't find the mako file).

I'd *guess* that either `webCtntPath` in `settings.py` is not actually a valid path, or you have a casing issue. I haven't done a lot of poking about with the Windows Subsystem for Linux, but it wouldn't surprise me if it emulates a case sensitive filesystem, whereas the rest of windows does not.

I've had issues with git in the interaction of a windows computer with a linux fileshare, where windows doesn't notice if the casing of a filename has changed, and yet linux can't find the file in question any more.

**Comment by fake-name** [comment]
Also, FWIW, you shouldn't need to do a clean re-clone for changed. Just `git pull` in the repo should bring everything up to date.

**Comment by mmsterful** [comment]
Problem solved: I forgot to update my settings after moving it between drives. >_<

**Comment by mmsterful** [comment]
It's working fine with one artist and the FA login method you added; soon I'll test that mass-add script out.

**Comment by mmsterful** [comment]
50 gigabytes down so far and no problems!

**Comment by fake-name** [comment]
Hahahaha, nice!
