### ISSUE TITLE
new sqllite fails to open itself on first start (and after)

### ISSUE THREAD

**Issue by CuddleBear92** [fake-name/xA-Scraper#50]
new sqllite fails to open itself on first start (and after).
this happens on a fresh master download aswell mind you so out of the box it fails. unsure where the error is though.

```Running migrator!
Traceback (most recent call last):
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 328, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1229, in _do_get
    return self._create_connection()
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "db_migrate.py", line 53, in <module>
    manager.run()
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 73, in <module>
    run_migrations_online()
  File "migrations/env.py", line 59, in run_migrations_online
    connection = engine.connect()
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2091, in connect
    return self._connection_cls(self, **kwargs)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2177, in raw_connection
    self.pool.unique_connection, _connection)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 328, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1229, in _do_get
    return self._create_connection()
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/mnt/e/xScraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

**Comment by fake-name** [comment]
This sounds a lot like the path for the sqlite database isn't valid, or isn't writable. Can the scraper create files in it's working directory?

**Comment by CuddleBear92** [comment]
didnt actually touch the settings for the sqlite path as it seemed it was self setting.

would expect it to try to make the database in its base directory and read it from there. and the script dont have any issues creating and writing the vevn folders and contents like pip and so on.

```
	"sqlite" :
	{
		"sqlite_db_path" : os.path.abspath(os.path.join("./", "sqlite_db.db"))
	},
```

**Comment by fake-name** [comment]
Yeah, ` os.path.abspath(os.path.join("./", "sqlite_db.db"))` just *should* resolve out to the current working directory, which is why I'm confused. Is it possible you're invoking the script from another path? E.g. `python /path/to/script.py`? In that case, the cwd of the shell you're invoking the scraper from would be where it tries to drop the database.

You could try replacing the `"./'` with `os.path.dirname(__file__)`, which should force the database to be located in the same directory as the python files.

Mostly, it's the way it is because I can see contexts where you would want both behaviours. Right now, it's possible for the python directory to be read-only, and executed from another location.

**Comment by CuddleBear92** [comment]
i guess that would be something like this: 

```
"sqlite_db_path" : os.path.abspath(os.path.join("/mnt/e/xA-Scraper-master/", "sqlite_db.db"))
```
where it would just point to the base script folder. 
that left me with the  same error sadly.

**Comment by fake-name** [comment]
You shouldn't need to bother with the path stuff if you're specifying the path as an absolute path:

```

**Comment by CuddleBear92** [comment]
having it as 
`os.path.dirname(__file__)` instead of ./ sadly leaves me with the same error aswell.

the script dont have issues writing the venv folder and files so it shouldnt have issues writing anything in the folder itself.

also think that the linux in windows users does have windows admin rights all over if i recall right.

**Comment by fake-name** [comment]
Yeah, I have no idea *what* is going on. Possibly it's something linux-subsystem-for-windows related.

I really only have the facilities to test on plain-old linux.  I don't even have a windows 10 box, actually.

**Comment by CuddleBear92** [comment]
well i feel i really don't need linux as your script is the only one that doesn't work even for the few linux only scripts and programs i have XD

i might have to try to roll back to an earlier commit before the sqllite stuff was added as it was working fine till i updated to that.

**Comment by fake-name** [comment]
Is there a reason you're using WSL for this? I know it's whizz-bang and fancy and all, but it seems like it just adds a lot more complexity into the whole situation. As I understand it, Sqlite does a lot of interesting file-locking and such on the db file, and I'd imagine mapping that through two different filesystem ACL representations wouldn't exactly be straightforward.

If you're not using SQLite, why do you have it enabled?

**Comment by fake-name** [comment]
Also: Huh - https://github.com/Microsoft/WSL/issues/2395

**Comment by CuddleBear92** [comment]
well it allows me to actually run bash scripts without too many issues without the need of a virtual box or any of the sort. just sounds like less hassle to me to have it all built into cmd and such.

and yeah i did have a postgres install and database and i have tried both options. removing the requirement to actually use and have postgres installed would be much better. + would be easier to back up the sqllite database and such in the end.

**Comment by fake-name** [comment]
Well, it should work on plain windows, or plain linux with sqlite. It just sounds like WSL's filesystem layer + sqlite is kind of asplody at the moment.

**Comment by CuddleBear92** [comment]
locks not respected? thats not a good thing. could lead to a lot of errors i would think.

but in the end i have tried with and without postgres on my old install and a fresh one and i get different errors and such on all my options.

**Comment by CuddleBear92** [comment]
only other thing i could try would be to have a full linux install. but for one script? even if its patreon and even if this script is one of the few out there it seems that support it.

only reason i actually use this is cause of patreon.

**Comment by fake-name** [comment]
Try it on plain windows (without WSL)?

**Comment by CuddleBear92** [comment]
cant actually run any bash scripts without wsl as it is bash and linux as a whole. and its also build into cmd and powershell after its installed.

**Comment by CuddleBear92** [comment]
atleast thats from my experience as a noob that figures it out as i go.
never had great success with any bash scripts when i dont have wsl, the few i have used in the past anyway.

**Comment by fake-name** [comment]
You don't need bash to run anything in the scraper other then the run.sh script, which is like 6 lines. 

Just either hand-roll your own venv, or install the requirements into the global python install, and run `python main.py`.

**Comment by CuddleBear92** [comment]
fair enough, doing that now.
running main and checking for errors and pip3 installing missing stuff.

**Comment by CuddleBear92** [comment]
sad to report that i couldnt figure this out myself sadly.
tried alot of things, but in the end i rolled back to a version that worked for my setup.

did try to get the scraper running on my synology linux box though! that didnt go so smoothly either sadly. that came down to python versioning i think.

**Comment by fake-name** [comment]
Huh, that's a bummer.

If you have error outputs, I can probably fix whatever the issue was.

**Comment by panpanick** [comment]
Hey, I'm getting this exact same problem. My console output looks like this after seeing all of the `Requirement already up-to-date` messages:

```
Installing collected packages: astor, ChromeController
  Found existing installation: astor 0.6.2
    Uninstalling astor-0.6.2:
      Successfully uninstalled astor-0.6.2
  Running setup.py install for astor ... done
  Found existing installation: ChromeController 0.1.7
    Uninstalling ChromeController-0.1.7:
      Successfully uninstalled ChromeController-0.1.7
  Running setup.py install for ChromeController ... done
Successfully installed ChromeController-0.1.7 astor-0.6.2
Launching executable.
Sqlite database path: 'sqlite:///home/pan/cy_patreon/xA-Scraper/sqlite_db.db'
/home/pan/cy_patreon/xA-Scraper/rewrite/__init__.py:68: ExtDeprecationWarning: Importing flask.ext.markdown is deprecated, use flask_markdown instead.
  from flask.ext.markdown import Markdown
/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/flask/exthook.py:106: ExtDeprecationWarning: Detected extension named flaskext.markdown, please rename it to flask_markdown. The old form is deprecated.
  .format(x=modname), ExtDeprecationWarning
Running migrator!
Traceback (most recent call last):
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 345, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 784, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1280, in _do_get
    return self._create_connection()
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 667, in __connect
    connection = pool._invoke_creator(self)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "db_migrate.py", line 53, in <module>
    manager.run()
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 73, in <module>
    run_migrations_online()
  File "migrations/env.py", line 59, in run_migrations_online
    connection = engine.connect()
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2102, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
    self.pool.unique_connection, _connection)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 345, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 784, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1280, in _do_get
    return self._create_connection()
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 667, in __connect
    connection = pool._invoke_creator(self)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/pan/cy_patreon/xA-Scraper/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by fake-name** [comment]
Oh *wow*, that's embarrasing. It turns out the issue is I'm missing *another* slash in the sqlite database URI. It needs to be something like `sqlite:////absolute/fs/path/sqlite_db.db`, rather then `sqlite:///absolute/fs/path/sqlite_db.db` (which is what I had been using.

The logic for having one leading slash be a *relative* path is beyond me.

Of course, that exposed a further sqlite issue from my fix of https://github.com/fake-name/xA-Scraper/issues/75.

The wierd thing is I could *swear* I had tested that at one point. I wonder why it worked.

**Comment by fake-name** [comment]
Ok, I think that should actually resolve the issue. Note: you *will* need to edit your `settings.py` file (since that's where the Sqlite URI is specified).

You'll need to change [line ~214](https://github.com/fake-name/xA-Scraper/blob/master/settings.base.py#L214). Another slash needs to be added to the `sqlite://{db_path}` section -> `sqlite:///{db_path}`.

**Comment by panpanick** [comment]
Oh wow, that was fast!

After pulling the latest commit and trying again, there is only this error `ImportError: No module named 'flask_markdown'` which is solved by `pip install flask-markdown` and then changing line 68 in rewrite/__init__.py to `from flaskext.markdown import Markdown`

**Comment by fake-name** [comment]
Lol, derp. Forgot to update the requirements.
