### ISSUE TITLE
fails to start after upgrading older version to newest master

### ISSUE THREAD

**Issue by CuddleBear92** [fake-name/xA-Scraper#51]
getting a list of errors when trying to load my main old postgres based setup. 
here is the traceback:

```
Running migrator!
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/util/messaging.py:69: UserWarning: Revision 6ac11f48bcca is present more than once
  warnings.warn(msg)
Traceback (most recent call last):
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/base.py", line 143, in _catch_revision_errors
    yield
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/base.py", line 334, in _upgrade_revs
    revs = list(revs)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/revision.py", line 656, in _iterate_revisions
    uppers = util.dedupe_tuple(self.get_revisions(upper))
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/revision.py", line 301, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/revision.py", line 445, in _resolve_revision_number
    current_head = self.get_current_head(branch_label)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/revision.py", line 271, in get_current_head
    "%s@head" % branch_label if branch_label else "head")
alembic.script.revision.MultipleHeads: Multiple heads are present for given argument 'head'; 355a8f844fb8, 916e4599f92d, f058fce52fad

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "db_migrate.py", line 53, in <module>
    manager.run()
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file    module = load_module_py(module_id, path)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 73, in <module>
    run_migrations_online()
  File "migrations/env.py", line 66, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/command.py", line 243, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/base.py", line 338, in _upgrade_revs
    for script in reversed(list(revs))
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/base.py", line 168, in _catch_revision_errors
    compat.raise_from_cause(util.CommandError(multiple_heads))
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/util/compat.py", line 194, in raise_from_cause    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/util/compat.py", line 187, in reraise
    raise value.with_traceback(tb)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/base.py", line 143, in _catch_revision_errors
    yield
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/base.py", line 334, in _upgrade_revs
    revs = list(revs)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/revision.py", line 656, in _iterate_revisions
    uppers = util.dedupe_tuple(self.get_revisions(upper))
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/revision.py", line 301, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/revision.py", line 445, in _resolve_revision_number
    current_head = self.get_current_head(branch_label)
  File "/mnt/e/xA-Scraper-master/venv/lib/python3.5/site-packages/alembic/script/revision.py", line 271, in get_current_head
    "%s@head" % branch_label if branch_label else "head")
alembic.util.exc.CommandError: Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads
```

**Comment by fake-name** [comment]
This sounds like some of the older migrations (the files in https://github.com/fake-name/xA-Scraper/tree/master/migrations/versions) didn't get deleted when updating, somehow, when updating.

What do you get if you run `git clean -fxdn`? This will tell you untracked files in the repo. Is this a clean checkout?

**Comment by fake-name** [comment]
Closing due to age.
