### ISSUE TITLE
Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object

### ISSUE THREAD

**Issue by ImportTaste** [fake-name/xA-Scraper#59]
>python db_migrate.py db upgrade && python main.py
```
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
Running migrator!
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade b7e0935213d5 -> 46e1cef59e06, Fix Pixiv URLs for new format
Getting Pixiv DB Entries
Fixing database entries
0it [00:00, ?it/s]
Migrated!
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
Setting up loggers....
done
Main.Runtime - INFO - Go()
Creating pool
INFO: Creating engine for process! Engine name: 'MainProcess-MainThread'
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
apscheduler.scheduler - INFO - Added job "fa" to job store "default"
apscheduler.scheduler - INFO - Added job "fa" to job store "default"
apscheduler.scheduler - INFO - Added job "hf" to job store "default"
apscheduler.scheduler - INFO - Added job "hf" to job store "default"
apscheduler.scheduler - INFO - Added job "wy" to job store "default"
apscheduler.scheduler - INFO - Added job "wy" to job store "default"
apscheduler.scheduler - INFO - Added job "ib" to job store "default"
apscheduler.scheduler - INFO - Added job "ib" to job store "default"
apscheduler.scheduler - INFO - Added job "sf" to job store "default"
apscheduler.scheduler - INFO - Added job "sf" to job store "default"
apscheduler.scheduler - INFO - Added job "ng" to job store "default"
apscheduler.scheduler - INFO - Added job "ng" to job store "default"
apscheduler.scheduler - INFO - Scheduler started
apscheduler.scheduler - INFO - Scheduler started
apscheduler.scheduler - DEBUG - Looking for jobs to run
apscheduler.scheduler - DEBUG - Looking for jobs to run
Main.Runtime - INFO - Scheduler is running!
apscheduler.scheduler - DEBUG - Next wakeup is due at 2019-09-29 01:00:00-05:00 (in 148792.535664 seconds)
Main.Runtime - INFO - Launching server process
apscheduler.scheduler - DEBUG - Next wakeup is due at 2019-09-29 01:00:00-05:00 (in 148792.535664 seconds)
Main.Runtime - INFO - Entering idle loop.
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
No settings for plugin key px. Skipping
No settings for plugin key pat. Skipping
No settings for plugin key da. Skipping
No settings for plugin key ay. Skipping
No settings for plugin key as. Skipping
No settings for plugin key yp. Skipping
No settings for plugin key tum. Skipping
[27/Sep/2019:07:40:11] ENGINE Bus STARTING
[27/Sep/2019:07:40:11] ENGINE Started monitor thread 'Autoreloader'.
[27/Sep/2019:07:40:13] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x0000025AFD196F48>>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\portend.py", line 115, in free
    Checker(timeout=0.1).assert_free(host, port)
  File "C:\Python37\lib\site-packages\portend.py", line 69, in assert_free
    list(itertools.starmap(self._connect, info))
  File "C:\Python37\lib\site-packages\portend.py", line 85, in _connect
    raise PortNotFree(tmpl.format(**locals()))
portend.PortNotFree: Port 127.0.0.1 is in use on 6543.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cherrypy\process\wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "C:\Python37\lib\site-packages\cherrypy\_cpserver.py", line 180, in start
    super(Server, self).start()
  File "C:\Python37\lib\site-packages\cherrypy\process\servers.py", line 177, in start
    portend.free(*self.bind_addr, timeout=Timeouts.free)
  File "C:\Python37\lib\site-packages\portend.py", line 119, in free
    raise Timeout("Port {port} not free on {host}.".format(**locals()))
portend.Timeout: Port 6543 not free on 127.0.0.1.

[27/Sep/2019:07:40:13] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cherrypy\process\wspbus.py", line 268, in start
    self.publish('start')
  File "C:\Python37\lib\site-packages\cherrypy\process\wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: Timeout('Port 6543 not free on 127.0.0.1.')

[27/Sep/2019:07:40:13] ENGINE Bus STOPPING
[27/Sep/2019:07:40:13] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 6543)) already shut down
[27/Sep/2019:07:40:13] ENGINE Stopped thread 'Autoreloader'.
[27/Sep/2019:07:40:13] ENGINE Bus STOPPED
[27/Sep/2019:07:40:13] ENGINE Bus EXITING
[27/Sep/2019:07:40:13] ENGINE Bus EXITED
```
Nothing is running on port 6543, I checked. I downgraded xA-Scraper to https://github.com/fake-name/xA-Scraper/commit/70fb7c92409e17d2b5b3b7e98836f02638d5bc79 after this and it started fine.

**Comment by ImportTaste** [comment]
Fixed

**Comment by fake-name** [comment]
It's worth noting that linux can be cranky about allowing applications to take over a port a service was previously on. There's some mechanism for preventing a application from basically taking over a communication channel from another application by killing it and then opening the same ports. 

If you're restarting the app fairly quickly, it can happen pretty easily. Generally, you wait ~10 seconds or so and try again, and it works.
