### ISSUE TITLE
Internal Error on manual FA login: 'WebGetRobust' object has no attribute 'syncCookiesFromFile'

### ISSUE THREAD

**Issue by Aidolii** [fake-name/xA-Scraper#95]
When trying to log into FA, it gives me this error and fails to log in.

```
<Request 'http://127.0.0.1:6543/doFaCaptchaLogin' [POST]>
POST
Login values: {'action': 'login', 'name': 'EDITED-OUT-IN-NOTEPAD', 'pass': 'EDITED-OUT-IN-NOTEPAD', 'g-recaptcha-response': '', 'use_old_captcha': 1, 'captcha': '4kn9c', 'login': 'Login to FurAffinity'}
<Response [302]>
<RequestsCookieJar[<Cookie a=2392dcba-c540-491f-bfab-6ed447680eb6 for .furaffinity.net/>]>
Cookie:  a 2392dcba-c540-491f-bfab-6ed447680eb6
{'a': '2392dcba-c540-491f-bfab-6ed447680eb6'}
---------session----------
<RequestsCookieJar[<Cookie __cfduid=d0957bcb13b86085ea44c60e7ccae11a61523429687 for .furaffinity.net/>, <Cookie a=2392dcba-c540-491f-bfab-6ed447680eb6 for .furaffinity.net/>, <Cookie b=7f8995e2-ff72-4460-a9a6-6e8436bc5051 for .furaffinity.net/>]>
Cookie:  __cfduid d0957bcb13b86085ea44c60e7ccae11a61523429687
Cookie:  a 2392dcba-c540-491f-bfab-6ed447680eb6
Cookie:  b 7f8995e2-ff72-4460-a9a6-6e8436bc5051
{'__cfduid': 'd0957bcb13b86085ea44c60e7ccae11a61523429687', 'a': '2392dcba-c540-491f-bfab-6ed447680eb6', 'b': '7f8995e2-ff72-4460-a9a6-6e8436bc5051'}
[2018-04-11 01:54:57,624] ERROR in app: Exception on /doFaCaptchaLogin [POST]
Traceback (most recent call last):
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "E:\xA-Scraper\xA-Scraper-master\rewrite\views\fa_manual_login.py", line 135, in doFaCaptchaLogin
    wg.syncCookiesFromFile()
AttributeError: 'WebGetRobust' object has no attribute 'syncCookiesFromFile'
Internal Error!
'WebGetRobust' object has no attribute 'syncCookiesFromFile'
Traceback (most recent call last):
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\xA-Scraper\python\python-3.6.3.amd64\lib\site-packages\flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "E:\xA-Scraper\xA-Scraper-master\rewrite\views\fa_manual_login.py", line 135, in doFaCaptchaLogin
    wg.syncCookiesFromFile()
AttributeError: 'WebGetRobust' object has no attribute 'syncCookiesFromFile'
```

**Comment by fake-name** [comment]
I think you might need to update your dependencies. 

Can you run `pip install --upgrade -r requirements.txt` from the repo root?

**Comment by Aidolii** [comment]
I ran that command and tried again. No use, same error.

The upgrade did say that pyreadline was deprecated, however. Not sure if that is related.

**Comment by fake-name** [comment]
Yeah, I moved the `syncCookiesFromFile()` call to a semi-private one (because it is), and forgot to update it everywhere I use it.

Also, derp.

Should be fixed, I think?
